---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "P@ssw0rd"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "P@ssw0rd"
  MYSQL_REPLICATION_PASSWORD: "P@ssw0rd"
  MYSQL_DATABASE: "starrail"
  TZ: "Asia/Bangkok"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        envFrom:
        - secretRef:
            name: mysql-secret
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-migration
spec:
  template:
    spec:
      volumes:
      - name: shared-sql
        emptyDir: {}

      initContainers:
      - name: starrail-bak
        image: heftychonk/starrail-bak:20241224
        command: ["sh", "-c", "cp /starrail_bak.sql /data/starrail_bak.sql"]
        volumeMounts:
        - name: shared-sql
          mountPath: /data

      containers:
      - name: mysql-client
        image: mysql:8.0
        envFrom:
        - secretRef:
            name: mysql-secret
        command:
          - sh
          - -c
          - |
            mysql -hmysql-0.mysql.mysql.svc.cluster.local \
                  -uroot -p$MYSQL_ROOT_PASSWORD \
                  starrail < /data/starrail_bak.sql
        volumeMounts:
        - name: shared-sql
          mountPath: /data
      restartPolicy: Never
  backoffLimit: 4
