services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.8.1
    ports:
      - 127.0.0.1:9090:9090
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus/
    networks:
      - app-network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    volumes:
      - "/:/host:ro,rslave"

networks:
  app-network:
    name: app-network

volumes:
  prometheus_data:
  grafana_data:
