apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement-policy
  namespace: kube-system
spec:
  loadBalancerIPs: true
  externalIPs: true
  # interfaces:
  #   - ^eth[0-9]+$
  nodeSelector:
    matchExpressions:
      # Exclude control-plane nodes
      - key: node.kubernetes.io/exclude-from-external-load-balancers
        operator: DoesNotExist
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "nginx-ic-pool"
spec:
  blocks:
  - cidr: "192.168.1.240/28"
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
spec:
  blocks:
    - start: "192.168.1.220"
      stop: "192.168.1.229"
  serviceSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: NotIn
        values:
          - nginx-ingress
