---
- name: Install Docker and Docker Compose on EC2 instances
  hosts: ec2
  become: true
  tasks:
    - name: Update repository index
      ansible.builtin.dnf:
        update_cache: true
    - name: Install Docker
      ansible.builtin.dnf:
        name: docker.io
        state: present
    - name: Start Docker service
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true
    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.35.0/docker-compose-linux-x86_64
        validate_certs: false
        dest: "/usr/local/bin/docker-compose"
        mode: "0755"
