- name: Disable firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    enabled: false
    state: stopped

- name: Add disable firewalld to .bashrc
  ansible.builtin.blockinfile:
    path: "/home/{{ username }}/.bashrc"
    block: |
      # Disable firewalld
      sudo systemctl stop firewalld
      sudo systemctl disable firewalld
    state: present
    create: true
    append_newline: true
    prepend_newline: true
    mode: "0644"
