- name: Install Docker
  ansible.builtin.package:
    name: docker
    state: present

- name: Start Docker service
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.35.0/docker-compose-linux-x86_64
    validate_certs: false
    dest: "/usr/local/bin/docker-compose"
    mode: "0755"

- name: Create Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - docker
    append: true

- name: Include disable firewall task
  ansible.builtin.include_tasks: "disable-firewall-{{ ansible_distribution | lower }}.yml"
  when: ansible_distribution in ['Fedora', 'Ubuntu']
