cluster_name: talos-proxmox-cluster

# siderolabs/ecr-credential-provider extension requires talos version 1.11.0+ and k8s version 1.32+
talos_version: 1.12.12
schematic_id: 10e276a06c1f86b182757a962258ac00655d3425e5957f617bdc82f06894e39b # siderolabs/ecr-credential-provider extension (v1.35.0)
k8s_version: 1.37

vip: 192.168.1.30
enable_cilium_ingress: true
skip_cilium_connectivity_check: true
ecr_credential_provider:
  access_key:
  secret_key:
  accounts:
    -
