---
- name: Install Docker and Docker Compose
  hosts: all
  become: true
  pre_tasks:
    - name: Update repository index
      ansible.builtin.dnf:
        update_cache: true
  roles:
    - role: docker
      tags: docker

- name: Prepare development environment
  hosts: env_dev
  become: true
  roles:
    - role: dev_instance
      tags: dev_instance
