apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kind-metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.21.0.230-172.21.0.233
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kind-metallb-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - kind-metallb-ip-pool
